spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/atmdb
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
logging:
  file:
    name: ./log/blog.log
  level:
    root: INFO
jwt-variables: 
  KEY: atmProject
  ISSUER: koylumuhendis
  EXPIRES_ACCESS_TOKEN_MINUTE: 15